language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: curso-github-migueltomas
  on: master
  skip_cleanup: true
  api_key:
    secure: H4wMRD0gB3Rz38X74gIDLD3ZTDmC6hU1Duvhi+jMtICJALvAtmNV6qK9h2512RyZ0FoAhnY7riUIy1mmSLxPArz1zXxiav6nQwertMZKp7QI+U8B+5MTo1o7AOVJkcnsOxGdOYnbLg5/zxbd5V4ewftluiKsLhdjUO0SqB7pFpkzipzyJpiyeqShl4nN4YzRdX3Ml03AFZURLx0SyoBCiZujHL9AyAWz6A/7ON6AKFHABthAlpYiyBvd4d0A8OW61EF+kGeJ9s2ezvxIj+nBwdauD0maj3dJQxcspqkPXYttvWgRhR5FnAlg+nf4KoWNKD4DbO3iIrdekxiugzU7baACRHTeFy9P4X8SkFJEbANnqycBk/tiHE+l5dXcyatCXiVfoDolKNY9yM7vahMLSLjqSq37OxFR/JJtNV0iEmC2sTUflwraeSM8N6idGnaRY72YO9ou56175rUDt8+Qn/5L9NBd5Dx0sI6+YMvS0tl5/3hjAVz3+yG0wQEMxIKgs2xasLG+kUqONqBUg8jqkEEQy7nCumHndgnS/WqUET3ktNaiNL+3LYB42Uftj4SzyP6GR3aBQ+BqopDp6MSzkyP6/5AmJsR8bA1xF+by/lMmGMT3aOufoxxlJzWX8bBlPspJQ7Loj5xTcOE6wsR58BYwmR1X/cSEzul8ynf2XAg=