language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: curso-github-migueltomas
  on: master
  skip_cleanup: true
  api_key:
    secure: HXjdVo5m2GrcVTdZmHlzjaNeeFeRmGIMmAnH3Ps/ZvG4WzLxbzJLqcB3ceP5b+F+Jp3b9KOCUFnSl9QVMjVYMJ0RPhyfQZmZrBk5uFwwXPucd55MRdGwUbHD6YGvezPgcglhHUZi7rEJLOcUUPS7w9IpQyw2t8C/nVM5JpdexpZdibomHudgkbg9+L9bbsYdJvG1hTtRst6yiRHXEbttCT3EqbrIIQ6/uepixc4qVOOpkzt1C4IB2UNlJcEa8R8ThLq13aqIzwv+XkvBD7xOs1clrbXf1JbODk0X0eskT+DpLhuJvsdNHG0T2/2YCwVQVbG42Y1d7LUDw4nq03LxF38ISRneGsEJpbbGcBB6Wg40Hi3nD//NuDaQHspG5wK0W76Yc+U5A+Cx0qsSG6EewO6TK2MIAIrg+81o803YyVQrl1ZDvl8eTJwk1+nDqWfIg1w3oymJ8gNM9kzJBRmExmen1RE6j/+dP8xzeKiPaKzdoGGOsuKflZZ1mUP6JrV6g25B0ks/juht8lPP6erIWgzueruwiXQuQX83IuUJSyOz3OO6ZHJ7I6DMLjxBGEirm3sxfWl7PKZrYlFzoawSD1Hhxc0VZfIEc+cMcbC4nqx1pRGUr8zPl5jWNF8HM73iD0+B/gnUr6aAh/gjyu1Xhv0d0a2yszhq2HN/nzklf6k=
